// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: common.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalGateway_GetData_FullMethodName = "/common.InternalGateway/GetData"
)

// InternalGatewayClient is the client API for InternalGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalGatewayClient interface {
	GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error)
}

type internalGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalGatewayClient(cc grpc.ClientConnInterface) InternalGatewayClient {
	return &internalGatewayClient{cc}
}

func (c *internalGatewayClient) GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDataResponse)
	err := c.cc.Invoke(ctx, InternalGateway_GetData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalGatewayServer is the server API for InternalGateway service.
// All implementations should embed UnimplementedInternalGatewayServer
// for forward compatibility.
type InternalGatewayServer interface {
	GetData(context.Context, *GetDataRequest) (*GetDataResponse, error)
}

// UnimplementedInternalGatewayServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalGatewayServer struct{}

func (UnimplementedInternalGatewayServer) GetData(context.Context, *GetDataRequest) (*GetDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedInternalGatewayServer) testEmbeddedByValue() {}

// UnsafeInternalGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalGatewayServer will
// result in compilation errors.
type UnsafeInternalGatewayServer interface {
	mustEmbedUnimplementedInternalGatewayServer()
}

func RegisterInternalGatewayServer(s grpc.ServiceRegistrar, srv InternalGatewayServer) {
	// If the following call pancis, it indicates UnimplementedInternalGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalGateway_ServiceDesc, srv)
}

func _InternalGateway_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalGatewayServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalGateway_GetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalGatewayServer).GetData(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalGateway_ServiceDesc is the grpc.ServiceDesc for InternalGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "common.InternalGateway",
	HandlerType: (*InternalGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _InternalGateway_GetData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common.proto",
}
